name: Deploy to GitHub Pages (CRA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM config (disable audit/fund, add retries)
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000

      - name: Install deps (with retries)
        run: |
          npm ci || (echo "Retry 1 in 20s" && sleep 20 && npm ci) \
                 || (echo "Retry 2 in 40s" && sleep 40 && npm ci) \
                 || (echo "Retry 3 in 60s" && sleep 60 && npm ci)

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
